version: '3.8'

services:
  app:
    image: ivanhd/go-online-lawyer-app:alpine
    env_file:
      - .env
    networks:
      - gol_bridge
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/app
    restart: always
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_HOST=${DB_HOST}
    networks:
      - gol_bridge
    ports:
      - 5433:5433
    expose:
      - "5433"
    volumes:
      - postgres-db:/root/lib/data
    command: -p 5433
    hostname: ${DB_HOST}

volumes:
  postgres-db:

networks:
  gol_bridge:
    driver: bridge