version: '3.8'

services:
  app:
    container_name: api-go-lawyer
    build: .
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes: 
      - ./:/usr/src/app
    restart: always
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_HOST=${DB_HOST}
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/root/lib/data

volumes:
  postgres-db: